### ISSUE TITLE
Projects and Task Enhancements

### ISSUE THREAD

**Issue by wn-mitch** [wn-mitch/open-gtd#5]
# Projects
- [x] Create a parent task attribute
- [ ] Make a graph reader to properly display project nesting
- [ ] Create folders
- [ ] Set up basic folder structure based on projects
- [ ] Create parallel project type
- [ ] Create sequential project type
- [ ] Create project statuses
- [ ] Projects should have an info pane at the top
- [x] Tasks should be clickable on the projects pane
- [x] Create a top bar that lets you know which area of the system you are in rather than overloading the header

# Task Enhancements
- [ ] Make the project view say "no uncompleted tasks" when there aren't any tasks left
- [ ] Make the default filter status be "active"
- [x] Make tasks default sort by the due date, then the defer date, then the priority
- [ ] Make the sort headers clickable
- [ ] Change the task table to be a flex grid and not a table so that the column widths are semi-consistent
- [ ] New task should expand when you overflow the box
- [ ] Archived task's should be displayed when a toggle in the top bar is checked
- [ ] Priority should be made into custom user-created property
- [ ] Colors should snap to grey when they task is dropped or complete
- [ ] Tasks without dates should be moved to the bottom of a list
- [ ] Projects overview should show "No tasks" banner when filters clear out everything
- [ ] Inbox overview should show "No tasks" banner when filters clear out everything
